spring.application.name=user-service

#port number 
server.port=8081

#Eureka Server URL
eureka.client.service-url.defaultZone=http://localhost:9000/eureka

#PostgreSQL Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/marketgrid_user_db
spring.datasource.username=akshaydamarla
spring.datasource.password=Akshay@21

#JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update